exports.query={

    //queries of store
    getAllStores:'SELECT STOREID, STORENAME, CODE, ADDRESS FROM BMS.STORE;',
    saveStore:'INSERT INTO BMS.STORE (STORENAME, CODE, ADDRESS) VALUES($1, $2, $3);',
    updateStore:"UPDATE BMS.STORE SET STORENAME=$1, CODE=$2, ADDRESS=$3 WHERE STOREID=$4;",
    deleteStore:`DELETE FROM BMS.STORE WHERE STOREID=$1;`,
    getStoreDetails:`SELECT STOREID, STORENAME, CODE, ADDRESS,TITLE,ISBN,DESCRIBTION,AUTHER,publisher,PAGES
    FROM BMS.STORE INNER JOIN BMS.BOOK ON STORECODE=CODE
    WHERE STOREID=$1 ;`,
    getid:"SELECT STOREID FROM BMS.STORE;",
    getStoreCode:"SELECT  CODE FROM BMS.STORE;",


    //queries of book
    getAllBooks:"SELECT BOOKID, TITLE, ISBN, DESCRIBTION, AUTHER, PUBLISHER, PAGES, STORECODE FROM BMS.BOOK;",
    getBookDetails:`SELECT BOOKID, TITLE, ISBN, DESCRIBTION, AUTHER, PUBLISHER, PAGES, STORENAME,ADDRESS
    FROM BMS.BOOK INNER JOIN BMS.STORE ON STORECODE=CODE
    WHERE BOOKID =$1;`,
    saveBook:"INSERT INTO BMS.BOOK (TITLE, ISBN, DESCRIBTION, AUTHER, PUBLISHER, PAGES, STORECODE) VALUES($1, $2, $3, $4, $5, $6, $7);",
    updateBook:`UPDATE BMS.BOOK
    SET TITLE=$1, ISBN=$2, DESCRIBTION=$3, AUTHER=$4, PUBLISHER=$5, PAGES=$6, STORECODE=$7
    WHERE BOOKID=$8;`,
    deleteBook:`DELETE FROM BMS.BOOK WHERE BOOKID=$1;`,
    getBookId:"SELECT BOOKID FROM BMS.BOOK;",
}